// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2nsgH09fzSUGYRfJ0YOiIY1iqsbAkYVc',
    appId: '1:970333277244:web:c705c77dcf03e4656e0739',
    messagingSenderId: '970333277244',
    projectId: 'account-fec31',
    authDomain: 'account-fec31.firebaseapp.com',
    storageBucket: 'account-fec31.firebasestorage.app',
    measurementId: 'G-YRK40QWDFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1LHJg1d9D1jK7gq0dXxW2Nv5w92W1Pc',
    appId: '1:970333277244:android:2a9aaf0926756adb6e0739',
    messagingSenderId: '970333277244',
    projectId: 'account-fec31',
    storageBucket: 'account-fec31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOnLtmZdZYsQ_1ahgYFSrtFeU-a_-oOMY',
    appId: '1:970333277244:ios:dd96184af69e39bd6e0739',
    messagingSenderId: '970333277244',
    projectId: 'account-fec31',
    storageBucket: 'account-fec31.firebasestorage.app',
    androidClientId: '970333277244-33htcbkqrn5g8sao9go9tj8u14tu1ibf.apps.googleusercontent.com',
    iosClientId: '970333277244-ook69dkk66hred763bgrd3fc4ho1b77v.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOnLtmZdZYsQ_1ahgYFSrtFeU-a_-oOMY',
    appId: '1:970333277244:ios:dd96184af69e39bd6e0739',
    messagingSenderId: '970333277244',
    projectId: 'account-fec31',
    storageBucket: 'account-fec31.firebasestorage.app',
    androidClientId: '970333277244-33htcbkqrn5g8sao9go9tj8u14tu1ibf.apps.googleusercontent.com',
    iosClientId: '970333277244-ook69dkk66hred763bgrd3fc4ho1b77v.apps.googleusercontent.com',
    iosBundleId: 'com.example.accountApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2nsgH09fzSUGYRfJ0YOiIY1iqsbAkYVc',
    appId: '1:970333277244:web:a50455fd10d253bd6e0739',
    messagingSenderId: '970333277244',
    projectId: 'account-fec31',
    authDomain: 'account-fec31.firebaseapp.com',
    storageBucket: 'account-fec31.firebasestorage.app',
    measurementId: 'G-BKXTTX9K46',
  );
}
